name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    if: ${{ github.event.release.draft == false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: v12.x
    - name: Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
        npm publish ${{ github.event.release.assets[0].browser_download_url }} --access restricted
