name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'major | minor | patch'
        required: true
        default: 'minor'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: v12.x
    - run: npm ci
    - name: Bump Version
      id: version
      run: |
        VERSION=$(npm --no-git-tag-version version ${{ github.event.inputs.version }})
        echo "::set-output name=version::$VERSION"
    - name: Commit & Push
      id: commit
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add package.json
        git add package-lock.json
        git commit -m "VERSION"
        git push origin master
        echo "::set-output name=sha::$(git rev-parse HEAD)"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false
        commitish: ${{ steps.commit.outputs.sha }}
    - name: Pack
      id: pack
      run: |
        FILE_NAME=$(npm pack)
        echo "::set-output name=file_name::$FILE_NAME"
    - name: Upload Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.pack.outputs.file_name }}
        asset_name: ${{ steps.pack.outputs.file_name }}
        asset_content_type: application/gzip
