name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'major | minor | patch'
        required: true
        default: 'minor'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: v12.x
    - run: npm ci
    # - run: npm run build --if-present
    - name: Bump Version
      id: version
      run: |
        VERSION=$(npm --no-git-tag-version version ${{ github.event.inputs.version }})
        echo "::set-output name=version::$VERSION"
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: commit
      run: |
        # Stage the file, commit and push
        git add package.json
        git add package-lock.json
        git commit -m "VERSION"
        git push origin master

  release:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: v12.x
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ needs.version.outputs.version }}
        release_name: Release ${{ needs.version.outputs.version }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false
    - name: Pack
      id: pack
      run: |
        FILE_NAME=$(npm pack)
        echo "::set-output name=file_name::$FILE_NAME"
    - name: Upload Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.pack.outputs.file_name }}
        asset_name: ${{ steps.pack.outputs.file_name }}
        asset_content_type: application/gzip
